name = "ProtectedArrays"
uuid = "cc189d76-b79b-4429-8ac4-62283b8a79d2"
license = "MIT"
desc = "Array wrapper to prevent modifications"
authors = ["Federico Stra <stra.federico@gmail.com> and contributors"]
version = "0.1.0"

[weakdeps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"

[extensions]
ArrayLayoutsExt = "ArrayLayouts"

[compat]
julia = "1.9"
